import type { ConversationData, AccountData, DashboardOverview, FeatureSettings, BillingSummary, PlanData } from "./api";

export const mockAccount: AccountData = {
  id: "123e4567-e89b-12d3-a456-426614174000",
  businessName: "Summit Plumbing",
  category: "Plumbing",
  categoryId: 1,
  businessPhone: "+14155551234",
  phoneCountryCode: "US",
  email: "owner@summitplumbing.com",
  serviceArea: "San Francisco Bay Area",
  websiteUrl: "https://summitplumbing.com",
  businessHours: "Mon-Fri 8am-6pm, Sat 9am-2pm",
  forwardingPhone: "+14155559999",
  addressLine1: "123 Main Street",
  addressLine2: "Suite 100",
  city: "San Francisco",
  region: "California",
  regionId: null,
  postalCode: "94102",
  country: "United States",
  countryId: 1,
  countryCode: "US",
  plan: "Starter",
  planId: 2,
  includedMinutes: 250,
  billingPeriod: "Jun 1 - Jun 30",
  minutesUsed: 87,
  createdAt: "2024-01-15T00:00:00Z",
  hasPassword: true,
  hasGoogle: false,
  requiresCurrentPassword: true,
  emailCallNotifications: true,
  smsCallNotifications: false,
  greetingMessage: null,
  agentVoice: null,
};

export const mockConversations: ConversationData[] = [
  {
    id: "conv-1",
    callerName: "John Smith",
    callerPhone: "+14155550101",
    dateTimeUtc: "2024-06-15T14:30:00Z",
    durationSeconds: 245,
    language: "English",
    summary: "Customer has a leaking kitchen faucet. Needs repair scheduled for tomorrow morning. Address: 456 Oak Street, San Francisco.",
    status: "Completed",
  },
  {
    id: "conv-2",
    callerName: "Maria Garcia",
    callerPhone: "+14155550102",
    dateTimeUtc: "2024-06-15T11:15:00Z",
    durationSeconds: 180,
    language: "Spanish",
    summary: "Emergency call - burst pipe in basement. Technician dispatched immediately. Address: 789 Pine Avenue, Oakland. Priority: Emergency.",
    status: "Completed",
  },
  {
    id: "conv-3",
    callerName: "Robert Chen",
    callerPhone: "+14155550103",
    dateTimeUtc: "2024-06-14T16:45:00Z",
    durationSeconds: 120,
    language: "English",
    summary: "Routine maintenance inquiry. Annual maintenance check needed. Address: 321 Elm Street, Berkeley. Scheduled for next week.",
    status: "Completed",
  },
  {
    id: "conv-4",
    callerName: "Sarah Johnson",
    callerPhone: "+14155550104",
    dateTimeUtc: "2024-06-14T09:20:00Z",
    durationSeconds: 95,
    language: "English",
    summary: "Quote request for bathroom renovation. Sent estimate via email. Email: sarah.j@email.com.",
    status: "Completed",
  },
  {
    id: "conv-5",
    callerName: "Unknown",
    callerPhone: "+14155550105",
    dateTimeUtc: "2024-06-13T15:30:00Z",
    durationSeconds: 0,
    language: "English",
    summary: null,
    status: "Missed",
  },
];

export const mockDashboard: DashboardOverview = {
  plan: "Starter",
  includedMinutes: 250,
  minutesUsed: 87,
  remainingMinutes: 163,
  billingPeriod: "Jun 1 - Jun 30",
  conversationsAnswered: 23,
  avgConversationDurationSeconds: 180,
  recentConversations: mockConversations.slice(0, 4),
};

export const mockFeatureSettings: FeatureSettings = {
  answerQuestions: true,
  servicesInfo: "We offer residential and commercial plumbing services including leak repair, pipe installation, water heater repair, drain cleaning, and emergency services.",
  serviceAreas: "San Francisco Bay Area, East Bay, Peninsula",
  businessHours: "Mon-Fri 8am-6pm, Sat 9am-2pm, Emergency 24/7",
  emergencyAvailability: "24/7 emergency service available for burst pipes and severe leaks",
  pricingPolicy: "Free estimates for all jobs. Hourly rate: $125/hr. Emergency calls: $175/hr.",
  warrantyPolicy: "All work guaranteed for 1 year. Parts warranty per manufacturer.",
  frequentlyAskedQuestions: "Q: Do you offer free estimates?\nA: Yes, we provide free estimates for all jobs.\n\nQ: How quickly can you respond to emergencies?\nA: We typically arrive within 1-2 hours for emergencies.\n\nQ: Do you work on weekends?\nA: Yes, we offer Saturday service 9am-2pm and 24/7 emergency service.",
  additionalBusinessInfo: "Licensed, bonded, and insured. 15+ years of experience. Family-owned business.",
  serveArea: true,
  distanceKm: 50,
  quoteInspection: true,
  pricePerKm: 2.50,
};

export const mockBillingSummary: BillingSummary = {
  plan: "Starter",
  includedMinutes: 250,
  minutesUsed: 87,
  remainingMinutes: 163,
  billingPeriod: "Jun 1 - Jun 30",
  usagePercent: 34.8,
};

export const mockPlans: PlanData[] = [
  {
    id: 1,
    name: "Free",
    priceMonthly: 0,
    includedMinutes: 25,
    hasOptionalFeatures: false,
    features: [
      "24/7 AI receptionist",
      "Multilingual support",
      "Customer intake",
      "Call summaries",
      "25 included minutes",
    ],
  },
  {
    id: 2,
    name: "Starter",
    priceMonthly: 49,
    includedMinutes: 250,
    hasOptionalFeatures: false,
    features: [
      "24/7 AI receptionist",
      "Multilingual support",
      "Customer intake",
      "Call summaries",
      "250 included minutes",
    ],
  },
  {
    id: 3,
    name: "Business",
    priceMonthly: 99,
    includedMinutes: 1000,
    hasOptionalFeatures: true,
    features: [
      "24/7 AI receptionist",
      "Multilingual support",
      "Customer intake",
      "Call summaries",
      "1,000 included minutes",
      "Answers questions about services",
    ],
  },
];
